### ISSUE TITLE
QXcbConnection: Could not connect to display

### ISSUE THREAD

**Issue by jiaxing912** [cozygene/glint#1]
when I run: 
python glint.py --datafile datafile.glint --plot --plotpcs --numpcs 2 --out pcs_plot

I got an error:
INFO      Starting GLINT...
INFO      Validating arguments...
INFO      Loading glint file datafile.glint...
INFO      Running PCA...
INFO      Plotting first 2 PCs...
QXcbConnection: Could not connect to display 
Aborted (core dumped)

so I couldn't get the .png figure.

what should I do?

**Comment by E-R** [comment]
I deeply apologize for this late reply. I was accidentally marked as "not watching" for notifications on this project.

I'm guessing that you're running GLINT on a remove server? It looks like you haven't used X11 forwarding, which is what allows GLINT (or any other software on the server) to display graphics, such as the PCA plot you were trying to generate in this example.

Here's a good source explaining how to allow X11 forwarding, depending on your operating system:
https://www.hoffman2.idre.ucla.edu/access/x11_forwarding/

I have added a note about enabling X11 forwarding when using the --plot flag.
