### ISSUE TITLE
Help with GLINT set up

### ISSUE THREAD

**Issue by sfrischm** [cozygene/glint#11]
Hello,

I'm very new to all of this, please pardon the novice question.

I have installed GLINT, but don't know what to do to complete the set up and begin to use it.

Can you guide me through this?

Thanks,
Sarah

**Comment by E-R** [comment]
If you installed GLINT by following the instructions in the README then you should be able to start using it right away. You can see the full documentation of GLINT [here](https://glint-epigenetics.readthedocs.io/en/latest/); particularly, it includes a [quick start tutorial](https://glint-epigenetics.readthedocs.io/en/latest/tutorial.html) which I'd recommend you going through.
