### ISSUE TITLE
Install Issue - R/RStudio

### ISSUE THREAD

**Issue by cewim** [cozygene/glint#15]
Hello,

I am interested in using GLINT for DNA methylation analysis in R/RStudio. I've downloaded the source package and unzipped the file. However, I'm running into an issue with the installation.

`install.packages("~/Downloads/glint-1.0.4/glint-1.0.4", repos = NULL, type="source")`

> Warning: invalid package '~Documents/Downloads/glint-1.0.4/glint-1.0.4'
> Error: ERROR: no packages specified
> Warning in install.packages: installation of package ‘ ~/Downloads/glint-1.0.4/glint-1.0.4’ had non-zero exit status

I'm running R 4.3.1 in RStudio on Windows 10, if that helps. My working directory is also set to the folder that is the source file.

Any ideas what I might be doing wrong?

Many thanks,

Courtney

**Comment by E-R** [comment]
glint is a command-line based python package and cannot be installed as an R package. Please see the README file for details.
