### ISSUE TITLE
ImportError: No module named abc

### ISSUE THREAD

**Issue by angelcymak** [cozygene/glint#4]
I use Anaconda python and installed cvxplot and received the following error when running the tutorial. I googled and found that abc was deprecated https://github.com/crossbario/crossbar/issues/1371. Is my issue relevant to the problem discussed in the link?

 File "/home/demo/.local/lib/python2.7/site-packages/statsmodels/tools/validation/validation.py", line 1, in <module>
    from collections.abc import Mapping
ImportError: No module named abc

**Comment by E-R** [comment]
Sorry for the late reply.
If this is still relevant, can you please answer the following questions:
- What version of python are you using?
- What version of Anaconda are you using?
- Can you send the exact command that leads to this error?
