### ISSUE TITLE
Could not replicate the tutorial results!

### ISSUE THREAD

**Issue by moqri** [cozygene/glint#6]
I am following your tutorial but cannot get the same results.
My final results plot looks like this:
![image](https://user-images.githubusercontent.com/4342458/89202249-80f35580-d567-11ea-9a29-5d999ebf3efa.png)

Which is different than the one in the tutorial! My code is also here: 
https://github.com/moqri/Aging-and-DNA-Methylation/blob/master/glint.ipynb

**Comment by E-R** [comment]
Your final results are fine! I've made some small changes with the tutorial files and forgot to update the new figures in the tutorial page -- now corrected. Thanks.

**Comment by moqri** [comment]
Thanks for the quick update!
